### PR TITLE
Update to support newest version of chai

### PR DESCRIPTION
**Pull request by hexpunk**
@joshperry I've been using karma-dirty-chai extensively with the newest version of chai (4.1.2), which dirty-chai [already supports](https://github.com/prodatakey/dirty-chai/blob/53a0def42c752c044c78b5544ba69de75231c44f/package.json#L40) as well.  No issues thus far.

Can you please merge this and publish a patch version (or however you prefer) so that I can stop getting yarn/npm warnings about peer dependency mismatches?  Thank you!

### CODE REVIEW

**Comment by hexpunk** [comment]
This PR will resolve #12.

**Comment by tregusti** [comment]
Please merge this, simple fix!

**Comment by JayCanuck** [comment]
@joshperry Would love to get this fix in asap

**Comment by hexpunk** [comment]
Any chance of a merge?

**Pull request closed without merging**
